import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    AUTH_SECRET: z.string().min(32),
    AUTH_URL: z.string().url().optional(),
    AUTH_RESEND_KEY: z.string().startsWith("re_"),
    AUTH_EMAIL_FROM: z.string().min(1),
    AUTH_GOOGLE_ID: z.string().min(1).optional(),
    AUTH_GOOGLE_SECRET: z.string().min(1).optional(),
    STRIPE_SECRET_KEY: z.string().startsWith("sk_"),
    STRIPE_PUBLISHABLE_KEY: z.string().startsWith("pk_"),
    STRIPE_WEBHOOK_SECRET: z.string().startsWith("whsec_"),
    STRIPE_TAX_RATE_ID: z.string().startsWith("txr_"),
    BLOB_READ_WRITE_TOKEN: z.string().startsWith("vercel_blob_rw_"),
    CRON_SECRET: z.string().min(32),
    JOURNAL_PREVIEW_SECRET: z.string().min(32),
    STRIPE_PRICE_MINI_NONE: z.string().startsWith("price_"),
    STRIPE_PRICE_MINI_6M: z.string().startsWith("price_"),
    STRIPE_PRICE_MINI_12M: z.string().startsWith("price_"),
    STRIPE_PRICE_CLASSIQUE_NONE: z.string().startsWith("price_"),
    STRIPE_PRICE_CLASSIQUE_6M: z.string().startsWith("price_"),
    STRIPE_PRICE_CLASSIQUE_12M: z.string().startsWith("price_"),
    STRIPE_PRICE_FAMILLE_NONE: z.string().startsWith("price_"),
    STRIPE_PRICE_FAMILLE_6M: z.string().startsWith("price_"),
    STRIPE_PRICE_FAMILLE_12M: z.string().startsWith("price_"),
    ADMIN_EMAIL: z.string().email(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_URL: process.env.AUTH_URL,
    AUTH_RESEND_KEY: process.env.AUTH_RESEND_KEY,
    AUTH_EMAIL_FROM: process.env.AUTH_EMAIL_FROM,
    AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    STRIPE_TAX_RATE_ID: process.env.STRIPE_TAX_RATE_ID,
    BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN,
    CRON_SECRET: process.env.CRON_SECRET,
    JOURNAL_PREVIEW_SECRET: process.env.JOURNAL_PREVIEW_SECRET,
    STRIPE_PRICE_MINI_NONE: process.env.STRIPE_PRICE_MINI_NONE,
    STRIPE_PRICE_MINI_6M: process.env.STRIPE_PRICE_MINI_6M,
    STRIPE_PRICE_MINI_12M: process.env.STRIPE_PRICE_MINI_12M,
    STRIPE_PRICE_CLASSIQUE_NONE: process.env.STRIPE_PRICE_CLASSIQUE_NONE,
    STRIPE_PRICE_CLASSIQUE_6M: process.env.STRIPE_PRICE_CLASSIQUE_6M,
    STRIPE_PRICE_CLASSIQUE_12M: process.env.STRIPE_PRICE_CLASSIQUE_12M,
    STRIPE_PRICE_FAMILLE_NONE: process.env.STRIPE_PRICE_FAMILLE_NONE,
    STRIPE_PRICE_FAMILLE_6M: process.env.STRIPE_PRICE_FAMILLE_6M,
    STRIPE_PRICE_FAMILLE_12M: process.env.STRIPE_PRICE_FAMILLE_12M,
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
